### ISSUE TITLE
rbs-inline auto-wire (#192) regresses in-source inference: return-chain and interprocedural folds lost, cross-owner singleton FP

### ISSUE THREAD

**Issue by zonuexe** [rigortype/rigor#194]
Filed from the rigor-rs port's differential-harness tracking (the same loop that fed c9d2e473 / 4e0ca475). Range bisected to the ADR-93 auto-wire wave: **`73141341..b70adcb5`** (PR #192, "Auto-wire the bundled rigor-rbs-inline plugin by default" + "Route standalone installs to rbs-inline when annotations go unread"). All repros are single-file, annotation-free, standalone (clean cwd, `--no-cache`) — no batch effects, no project sig, no config.

## Regression 1 — in-source return-chain inference lost

```ruby
# chain.rb
class Greeter
  def greeting
    "hello"
  end
end

g = Greeter.new
g.greeting.lenght
```

| | output |
|---|---|
| `7a69f142` (pre-wave) | `chain.rb:8:12: error: undefined method `lenght' for "hello"` |
| `b70adcb5` (master) | *(silent)* |

A true diagnostic is gone. The param-bound chain variant regresses identically.

## Regression 2 — interprocedural literal folds lost + cross-owner singleton FP

```ruby
# fold.rb
module Gitlab
  module Database
    def self.read_only?
      false
    end
  end
end

class Consumer
  def run
    if Gitlab::Database.read_only?
      puts "read-only"
    end
  end
end

class Unrelated
  def probe
    if Unrelated.read_only?
      puts "never"
    end
  end
end
```

| | output |
|---|---|
| `7a69f142` | `fold.rb:11:8: warning: condition is always falsey (…)` — and **silent** on `Unrelated` |
| `b70adcb5` | fold **gone**; `fold.rb:19:18: error: undefined method `read_only?' for singleton(Unrelated)` |

Two problems in one file: the v0.3.0 flagship interprocedural literal fold no longer fires, and the cross-owner case — the exact shape the own-class-resolution decline was built to keep silent (own-class `Unrelated` does not define `read_only?`; only `Gitlab::Database` does) — is now an FP.

## Mechanism (hypothesis, from the outside)

The auto-wire appears to synthesize in-source classes into RBS declarations even for **annotation-free** files in standalone mode, so the RBS dispatch tier answers before the in-source / interprocedural inference tiers:

- the chain return (`Greeter#greeting`) resolves against a synthesized signature (presumably `-> untyped`) instead of the in-source return-chain inference → the pinned `"hello"` is lost;
- in-source classes acquire a witnessable singleton surface → `Unrelated.read_only?` fires instead of declining.

## Not (necessarily) a bug, but worth a deliberate call

In multi-file runs, in-source classes defined in one analyzed file now resolve in *other* files and witness absences (2-file probe: `class Widget; def spin` in a.rb — b.rb's `w.spin` resolves, an absent method fires). That looks intended and is a genuine precision win, but it inverts the in-source-only leniency that FP-safety arguments elsewhere lean on — flagging it so the trade-off is explicit rather than incidental.

## Impact on the port (why we noticed)

Re-pinning rigor-rs's oracle at `b70adcb5` would turn 6 currently-correct diagnostics into oracle-FPs and drop the folds its fixtures pin byte-for-byte, so the pin is held at `7a69f142` until this is resolved. Happy to re-run the differential battery against any candidate fix.

**Comment by zonuexe** [comment]
> *This was generated by AI during triage.*

## Triage Notes

I could not reproduce any of the three reported behaviours in a faithful environment, so this needs a bit more from the harness side before it can move to an implementation state.

**How I verified.** Both repro files exactly as filed, single-file, annotation-free, clean cwd, `--no-cache`. Ran at the issue's `b70adcb5`, at pre-wave `7a69f142`, and at current `master` (`b2c196bf`, i.e. after #193). Auto-wire was confirmed **active** in the repro dir: `rigor plugins` shows `[OK] rbs-inline … config: {"require_magic_comment" => false}`, and `Gem::Specification.find_by_name("rbs-inline")` resolves to **0.14.0**.

**What I observed — identical at `b70adcb5`, `7a69f142`, and master:**

| check | reported @`b70adcb5` | observed (all three revs) |
| --- | --- | --- |
| `chain.rb` `g.greeting.lenght` | *silent* (regression) | `chain.rb:8:12: error: undefined method \`lenght' for "hello"` — **present** |
| `fold.rb` interprocedural fold | fold gone | `fold.rb:11:8: warning: condition is always falsey (…)` — **present** |
| `fold.rb` `Unrelated.read_only?` | FP `undefined method … singleton(Unrelated)` | **silent** — no FP |
| 2-file probe `w.nonexistent` | absent method fires | **No diagnostics** (identical with the plugin `enabled: false`) |

So in this environment the return-chain fold, the interprocedural literal fold, and the own-class-resolution decline all behave exactly as pre-wave, with auto-wire on.

**Why this most likely diverges.** The magic-comment-free mode gates on annotation *presence* (ADR-93 WD1): `Synthesizer#annotated?` delegates to upstream `RBS::Inline::AnnotationParser`, and an annotation-free file contributes **nothing** — no synthesized `-> untyped` skeleton, so the RBS tier never shadows the in-source / interprocedural tiers. That gate is exactly the fix ADR-93 WD4 "Finding 3" landed (2026-07-16, before #192) for the precise skeleton-shadowing mechanism this report hypothesises. The behaviour you're seeing is that gate **not holding** in the harness's environment — which points at the environment, not `b70adcb5`.

**What we still need from you (@zonuexe):**

- The **`rbs-inline` version** the differential harness resolves when it runs the oracle at `b70adcb5` — `bundle exec ruby -e 'p Gem::Specification.find_by_name("rbs-inline").version'` in the harness's env. (Mine: `0.14.0`. The `annotated?` gate delegates to upstream's `AnnotationParser`; a version whose parser/`each_annotation` surface differs could let an annotation-free file through — that would reproduce all of the above.)
- The **exact oracle invocation** at `b70adcb5`: full command line, any flags (`--treat-all-as-inline-rbs`?), any `.rigor.yml`/env, and whether it's the git-checkout `exe/rigor` at that commit or a packaged/standalone install.
- The **`rigor plugins`** output in the repro dir at `b70adcb5`: is `rbs-inline` loaded, with `require_magic_comment: false`, and what version does that row show?

Once I can see an annotation-free file actually contributing (i.e. `annotated?` returning true when it shouldn't, or the plugin loading a different `rbs-inline`), this becomes a concrete gate-hardening fix I can specify and land. The multi-file cross-file-resolution note is tracked separately from the two regressions above; happy to split it out once the primary mechanism is pinned.

**Comment by zonuexe** [comment]
Requested data from the harness side, plus new evidence that narrows the mechanism. Everything below re-verified today at the **exact SHA `b70adcb5`** (submodule checkout by hash, not a branch ref).

## 1. Requested environment data

| item | value |
|---|---|
| `rbs-inline` resolved by the oracle invocation | **0.14.0** — same as yours (`ruby -I <checkout>/lib -e 'p Gem::Specification.find_by_name("rbs-inline").version'`) |
| `prism` | 1.9.0 |
| Ruby | 4.0.5 (mise, arm64-darwin23) |
| Exact invocation | `ruby -I <git-checkout>/lib <git-checkout>/exe/rigor check <file> --no-cache` — plain `ruby -I lib` on the git checkout, **no bundler**, no `.rigor.yml`, no env vars, no `--treat-all-as-inline-rbs`; cwd is the repro dir |
| `rigor plugins` in the repro dir @ `b70adcb5` | `loaded: 1  load-error: 0` / `[OK ] rbs-inline v0.1.0 (rigor-rbs-inline) … source_rbs_synthesizer: yes … config: {"require_magic_comment" => false}` — matches yours |
| Gem-env noise (disclosed) | `Ignoring racc-1.8.1 … extensions are not built` and `Ignoring rbs-4.0.2 … extensions are not built` on every run; rbs resolves 4.0.3 |
| `bundle exec` A/B | **not runnable here** — the checkout's dev gems (rubocop etc.) aren't installed locally, `bundle exec` aborts on `GemNotFound`. So one honest env delta vs your verification stands: plain `-I lib` vs (presumably) a bundled context |

## 2. Your fail-open hypothesis, probed directly — it does NOT hold here

Ran the WD4-Finding-3 gate exactly as `Synthesizer#annotated?` does, in the same `-I lib` context, against `chain.rb`:

```
parsed results: 0
annotated? => false
```

The gate itself answers **false** for the annotation-free file in this environment. Whatever is contributing, it is not `annotated?` returning true.

## 3. Yet the plugin being LOADED is what flips the behavior

- **Bisect within the wave**: the regressions appear at **`861b08b9`** (the auto-wire commit itself) and persist through `9f57acaf` / `bc86f700` / `b70adcb5`.
- **A/B at `b70adcb5`**: with the plugin NOT loaded (a `plugins:` entry that fails to load — `loaded: 0 load-error: 1`), all three behaviors revert to pre-wave: `lenght` fires, the interprocedural fold fires, no `Unrelated` FP. Plugin loaded → all three regress.

## 4. One-file discriminator (crispest repro yet)

```ruby
# shell.rb
class Greeter
  def greeting
    "hello"
  end
end

g = Greeter.new
g.absent_method
```

| | output |
|---|---|
| `7a69f142` | *(silent — in-source-only leniency)* |
| `b70adcb5`, plugin `[OK]`, `annotated?`=false | `shell.rb:8:3: error: undefined method `absent_method' for Greeter` |

Together with `chain.rb` (where `greeting` *resolves* but the pinned `"hello"` chain is lost), this says: in this environment an annotation-free file's in-source class enters the environment as a **skeleton — methods present, returns untyped** — despite the gate probing false standalone. i.e. exactly the mode WD4 Finding 3 was built to prevent, arriving through some path other than the one I probed.

If `shell.rb` stays silent in your environment at `b70adcb5`, the divergence is environmental and the deltas to chase are: bundler vs plain `-I lib` gem activation, `prism` version (mine 1.9.0 — what does yours resolve?), and the broken-extension `rbs-4.0.2`/`racc` stubs RubyGems skips here. If it fires, you have the internal trace point.

Happy to run any diagnostic build/branch against the full differential battery.

**Comment by zonuexe** [comment]
> *This was generated by AI during triage.*

## Triage Notes (update 2)

Thank you — the bisect-to-`861b08b9`, the plugin-loaded A/B, and the standalone `annotated? => false` probe are exactly what was needed to rule out the obvious paths. It shifted my picture, so I re-verified harder. **I still cannot reproduce, now across two more environments**, which narrows the delta to a short list that no longer includes bundler-vs-plain.

**What I ran (all at `b70adcb5` unless noted), plugin confirmed `[OK]` / `require_magic_comment: false`, rbs-inline 0.14.0, prism 1.9.0:**

| environment | `shell.rb` `g.absent_method` | `chain.rb` `lenght` | `fold.rb` fold / `Unrelated` FP |
| --- | --- | --- | --- |
| `bundle exec exe/rigor` (flake, Ruby 4.0.3) | *silent* | fires | fires / no FP |
| plain `ruby -I lib -I plugins/rigor-rbs-inline/lib exe/rigor`, `GEM_HOME`→vendored (Ruby 4.0.3) | *silent* | fires | fires / no FP |
| your report (mise Ruby 4.0.5) | **fires** | *silent* | *gone* / **FP** |

So in **both** a bundled and a plain `-I lib` context here — plugin loaded, same gem versions — the in-source class does **not** enter as a skeleton: `shell.rb` stays silent, the `"hello"` chain keeps its literal, the fold fires, `Unrelated` declines. Your "bundler vs plain `-I lib`" delta is therefore **not** the trigger (I reproduced neither side of it as regressing).

**Remaining deltas, in priority order:**

1. **Ruby 4.0.5 (mise) vs 4.0.3 (flake).** This is now the prime suspect — it's the one axis I can't flip locally. `annotated?` delegates to upstream `RBS::Inline::AnnotationParser`, which parses the Prism comment stream; a patch-level Prism/Ruby difference in how comments attach could make the run-time gate diverge from your standalone probe.
2. The `Ignoring rbs-4.0.2 … extensions are not built` / `racc` stubs RubyGems skips in your env (my vendored set has only the built 4.0.3).

**Two discriminators that would localize it — both in your exact env at `b70adcb5`:**

- **Does it reproduce under Ruby 4.0.3?** `mise exec ruby@4.0.3 -- ruby -I lib exe/rigor check shell.rb --no-cache`. If it goes silent, it's a 4.0.4/4.0.5-specific interaction and we chase Prism/RBS behavior at that patch level; if it still fires, Ruby version is out and it's the gem-env stubs.
- **What type does `g.greeting` carry?** `ruby -I lib exe/rigor type-of chain.rb:8:3` with the plugin loaded vs `enabled: false`. `untyped` under the plugin = the in-source class was replaced by a synthesized skeleton (confirms the mechanism and gives the internal anchor); `"hello"` = the skeleton isn't the cause and we look elsewhere. Also worth capturing: the `Type universe → RBS classes available` count with the plugin on vs off — if `Greeter` is entering the RBS universe, the count moves.

Taking you up on the diagnostic-branch offer: once the Ruby-4.0.3 A/B is in, if it's version-specific I'll push a branch that logs, per project file, whether the synthesizer returned a contribution and what `annotated?` saw at run time (not standalone), so we can watch the skeleton appear in your env. Keeping this `needs-info` on those two data points; it flips to an actionable fix the moment we see `annotated?` disagree between run-time and standalone, or the skeleton in `type-of`.

**Comment by zonuexe** [comment]
**Root cause found — the reported engine regressions are withdrawn.** Your two discriminators localized it in one pass; full trace below, because what they uncovered IS an actionable upstream hazard, just a different one than filed.

## Discriminator results

- **`type-of chain.rb:8:3`**: `"hello"` with the plugin on AND off (caveat: I could not confirm `type-of` runs the auto-wire at all).
- **Universe count**: plugin on → **1349**, off → **1348**. The skeleton WAS entering — `Greeter`, one class.
- **Ruby 4.0.3 A/B**: first run was confounded (that env resolved rbs 3.10.0 / prism 1.8.1, no rbs-inline). After installing the matched set (rbs 4.0.3 / rbs-inline 0.14.0 / prism 1.9.0): the auto-wire **load-errors** — `could not load plugin gem "rigor-rbs-inline": cannot load such file`. That was the breadcrumb: under 4.0.5 the same `require` SUCCEEDS. From where?

## Root cause

```
$ gem which rigor-rbs-inline
…/gems/4.0.0/gems/rigortype-0.2.4/plugins/rigor-rbs-inline/lib/rigor-rbs-inline.rb
```

My Ruby 4.0.5 gem env has the **released `rigortype 0.2.4`** installed. The auto-wire's `require "rigor-rbs-inline"` resolves to **that gem's bundled plugin copy** — v0.2.4-era code that **predates the ADR-93 WD1 annotation gate entirely** (`grep -c 'annotated?'` in its `rbs_inline.rb`: **0**; it has only the old `require_magic_comment:` knob). The auto-wire passes `require_magic_comment: false` → old semantics = synthesize untyped skeletons for EVERY file — exactly the "26 → 42 on mail" mode WD4 Finding 3 killed. The runtime/standalone `annotated?` disagreement you predicted was real: the runtime never executed the gated code at all.

**Proof (all at `b70adcb5`, my env):** forcing the checkout's plugin onto the load path — `ruby -I lib -I plugins/rigor-rbs-inline/lib exe/rigor` — makes all three behaviors match yours: universe 1348, `shell.rb` silent, `chain.rb` fires `lenght`, `fold.rb` fold fires / no `Unrelated` FP. The 2-file cross-file probe ALSO goes silent — that observation is likewise withdrawn (stale-gem artifact, not a feature).

Your two no-repro environments never had a rigortype gem installed, so `require` fell through to the checkout path. My plain `-I lib` did not include `plugins/rigor-rbs-inline/lib`, so RubyGems won.

## The actual upstream hazard worth keeping this issue for

**Engine↔plugin version skew through the auto-wire.** A git-checkout (or any newer) rigor with an older rigortype gem installed silently loads the old gem's plugin copy: no version check, no provenance signal — `rigor plugins` prints an indistinguishable `[OK ] rbs-inline v0.1.0` in both cases (the plugin's own version constant never moved). The engine then runs with a plugin missing a load-bearing FP gate. This is the same installation-hazard class as the Gemfile-misuse guardrails (#114) and `doctor`'s Gemfile-installed-rigor report (#116). Suggestions, in increasing order of effort:

1. `rigor plugins` (and the load-error diagnostic) should print the **resolved file path** of each loaded plugin — this would have made the diagnosis a one-minute affair.
2. The auto-wire should prefer the engine's own bundled `plugins/` directory over gem resolution (the engine and its bundled plugins are versioned together; a gem-resolved copy is by definition skew-prone).
3. `doctor` could flag "plugin loaded from a different rigortype installation than the engine".

## Harness-side action (mine)

The port's oracle invocation will pin the checkout's plugin load path explicitly, and I'll re-run the differential battery for the wave with the corrected invocation — the "6 diagnostics become oracle-FPs" claim is presumed withdrawn along with the rest, will confirm.

Sorry for the noise on the regression framing — and the discriminator design was exactly right.

**Comment by zonuexe** [comment]
> *This was generated by AI during triage.*

## Triage resolution — engine regression withdrawn; re-scoped to the auto-wire version-skew hazard

Root cause confirmed and it is not an engine regression: **engine↔plugin version skew through the ADR-93 auto-wire**. Your Ruby 4.0.5 gem env has the released `rigortype 0.2.4` installed, so the auto-wire's `require "rigor-rbs-inline"` resolved to *that* gem's bundled plugin copy — code that predates the WD1 `annotated?` gate (`grep -c annotated? => 0`) and, under `require_magic_comment: false`, runs the old "synthesize an untyped skeleton for every file" mode (the 26→42-on-mail behaviour WD4 Finding 3 killed). My two no-repro environments had no `rigortype` gem installed, so `require` fell through to the checkout's gated plugin — which is exactly why the skeleton never appeared here (universe stayed 1348; yours moved to 1349). Thanks for the rigorous localization — the universe-count and Ruby-4.0.3 A/B discriminators pinned it in one pass, and withdrawing the two folds + the cross-file observation as stale-gem artifacts is the right call.

**Keeping this issue open, re-scoped to the retained hazard** — and it is a real one that #192 introduced: before the auto-wire, the plugin only loaded when a user listed it; now the engine `require`s a bundled plugin **by gem name** on every run, so a newer engine (git checkout, or a future upgrade) silently loads an *older* installed `rigortype`'s plugin copy, with no version check and no provenance signal — `rigor plugins` prints an indistinguishable `[OK] rbs-inline v0.1.0` either way. This is the same installation-hazard class as #114 / #116.

### Recommendation (from triage)

Category re-set to **bug** (the auto-wire silently loads a mismatched plugin copy and runs the engine with a missing FP gate → wrong diagnostics), `area:plugins`, `needs-info` cleared, **`ready-for-human`** — because the core fix is a resolution-order decision across install modes, not a mechanical change.

Your three suggestions, adopted with an effort split:

1. **Print each loaded plugin's resolved file path** in `rigor plugins` and in the `plugin_loader.load-error` diagnostic. Small, high-value, testable in isolation — this is splittable as a `ready-for-agent` slice and would have made this a one-minute diagnosis. Likely first.
2. **Auto-wire prefers the engine's own bundled `plugins/` over gem resolution** — the actual fix. The engine and its bundled plugins are versioned together, so a gem-resolved copy is skew-prone by definition. The judgment call held for a human: how the engine robustly locates its own bundled `plugins/` across the install modes (git checkout, installed `rigortype` gem, and the ADR-27 single-binary target) without reintroducing the ADR-27/31 auto-load concerns the WD2 gate was careful about.
3. **`doctor` flags "plugin loaded from a different `rigortype` installation than the engine"** — follow-on, builds on (1)'s resolved-path plumbing.

No engine change is needed for the originally-filed diagnostics; they were correct at the checkout's plugin version all along. Please go ahead and re-pin the port's oracle onto the checkout plugin path — the "6 diagnostics → oracle-FPs" concern should withdraw with the rest, and confirmation is welcome.

**Comment by zonuexe** [comment]
Confirmation, as requested — the port's oracle invocation now pins the checkout plugin path unconditionally ([rigor-rs PR #29](https://github.com/rigortype/rigor-rs/pull/29): `harness/lib.rb`, `fp_audit.py`, plus an `UPSTREAM.md` hazard note for ad-hoc probes), and the full battery was re-run with the corrected invocation at `7a69f142` vs `b70adcb5`:

| corpus | corrected wave delta |
|---|---|
| the port's 67-fixture differential corpus | **0 added / 0 dropped** |
| gitlab-foss `lib/` (4,676 files, 1,374 diags) | **0 / 0** |
| mastodon `app/models` | **0 / 0** |
| rbs-inline `lib/` (a genuinely `# @rbs`-annotated corpus) | **+13 / −0** — `def.override-param-narrowed` ×8 against `RBS::Inline::AST` types, `call.undefined-method` ×3, `call.possible-nil-receiver` ×2 |

The last row is the **intended** ADR-93 behavior — the annotation gate admitting files that really carry annotations — not a regression; from the port's side it becomes future coverage surface for the ADR-93/94 track, tracked separately.

So: the "6 diagnostics → oracle-FPs" concern is **withdrawn** with the rest; on unannotated code the wave is diagnostic-identical, and the port can re-pin at the tag whenever it lands. The issue's retained scope (auto-wire version-skew: resolved-path visibility → bundled-`plugins/`-preference → `doctor` skew flag) matches what I'd want as the oracle's consumer — (1) alone would have made this a one-minute diagnosis. Thanks for the sharp triage.
